// Syltalky — global data, mock state, i18n
window.MOCK_NOTES = [
  { id: 1, name: 'Họp nhóm dự án Q1 2026', type: 'file', modified: '24/04/2026', creator: 'Nguyễn Văn A', path: 'Công việc / Q1 2026', tags: ['quan-trọng'], starred: true,  deleted: false },
  { id: 2, name: 'Phiên họp khách hàng ABC', type: 'file', modified: '23/04/2026', creator: 'Nguyễn Văn A', path: 'Công việc / Khách hàng', tags: ['khách-hàng'],  starred: false, deleted: false },
  { id: 3, name: 'Dự án Syltalky',           type: 'folder',modified: '22/04/2026', creator: 'Nguyễn Văn A', path: '',                     tags: ['dự-án'],       starred: true,  deleted: false, children: [6,7] },
  { id: 4, name: 'Báo cáo tháng 4/2026',     type: 'file', modified: '21/04/2026', creator: 'Trần Thị B',   path: 'Báo cáo',               tags: [],              starred: false, deleted: false },
  { id: 5, name: 'Cuộc họp ban giám đốc',    type: 'file', modified: '20/04/2026', creator: 'Nguyễn Văn A', path: 'Công việc / Quản lý',   tags: ['quan-trọng'], starred: false, deleted: false },
  { id: 6, name: 'Tài liệu thiết kế UI',     type: 'file', modified: '22/04/2026', creator: 'Nguyễn Văn A', path: 'Dự án Syltalky',         tags: [],              starred: false, deleted: false, parentId: 3 },
  { id: 7, name: 'Yêu cầu chức năng',        type: 'file', modified: '20/04/2026', creator: 'Trần Thị B',   path: 'Dự án Syltalky',         tags: [],              starred: false, deleted: false, parentId: 3 },
  { id: 8, name: 'Sprint Review tháng 3',    type: 'file', modified: '18/04/2026', creator: 'Nguyễn Văn A', path: 'Công việc / Sprint',     tags: [],              starred: false, deleted: false },
];

window.MOCK_TRASH = [
  { id: 101, name: 'Ghi chú cũ tháng 3',       type: 'file',   deletedAt: '20/04/2026', creator: 'Nguyễn Văn A' },
  { id: 102, name: 'Thử nghiệm tính năng beta', type: 'file',   deletedAt: '15/04/2026', creator: 'Nguyễn Văn A' },
  { id: 103, name: 'Archive Q4 2025',           type: 'folder', deletedAt: '10/04/2026', creator: 'Trần Thị B'   },
];

window.RECENT_IDS = [1, 2, 5, 4, 3];

window.GUIDE_CONTENT = {
  vi: [
    {
      id: 'setup',
      color: '#00C9B8',
      title: 'Hướng dẫn thiết lập để vào cuộc họp',
      icon: 'setup',
      steps: [
        'Mở ứng dụng và đăng nhập vào tài khoản của bạn.',
        'Trên Sidebar, nhấn vào mục "Cuộc họp".',
        'Hệ thống sẽ hiện pop-up kiểm tra thiết bị — xác nhận Camera và Microphone hoạt động tốt.',
        'Nhấn "Sẵn sàng họp" để đọc lưu ý và nhấn "Bắt đầu họp" để vào phiên.',
        'Cửa sổ họp sẽ thu nhỏ — bạn có thể kéo và thay đổi kích thước tùy ý.',
      ]
    },
    {
      id: 'tips',
      color: '#7B61FF',
      title: 'Hướng dẫn để có kết quả nhận diện tốt nhất',
      icon: 'tips',
      steps: [
        'Đặt camera ở góc thẳng, đảm bảo cả hai tay luôn trong khung hình.',
        'Ánh sáng đều và đủ sáng — tránh ngược sáng.',
        'Giữ nền sau lưng đơn giản, ít chi tiết gây nhiễu.',
        'Thực hiện cử chỉ rõ ràng, không quá nhanh.',
        'Đảm bảo phòng yên tĩnh để nhận diện giọng nói chính xác hơn.',
      ]
    },
    {
      id: 'personalize',
      color: '#F97316',
      title: 'Cá nhân hóa trải nghiệm sử dụng',
      icon: 'personalize',
      steps: [
        'Vào Cài đặt → Cá nhân hóa để đổi giao diện Sáng / Tối.',
        'Chọn ngôn ngữ hiển thị: Tiếng Việt hoặc English.',
        'Vào Cài đặt → Phụ đề hiển thị để chỉnh cỡ chữ và font chữ phụ đề.',
        'Vào Cài đặt → Thiết bị để thay đổi mic, camera, loa mặc định.',
        'Mọi thay đổi được lưu tự động và áp dụng ngay lập tức.',
      ]
    },
  ],
  en: [
    {
      id: 'setup',
      color: '#00C9B8',
      title: 'Setup guide for joining a meeting',
      icon: 'setup',
      steps: [
        'Open the app and log in to your account.',
        'Click "Meeting" in the Sidebar.',
        'A device check pop-up will appear — verify your Camera and Microphone work.',
        'Click "Ready to Meet", review the tips, then click "Start Meeting".',
        'The meeting window will minimize — drag and resize it as needed.',
      ]
    },
    {
      id: 'tips',
      color: '#7B61FF',
      title: 'Tips for best recognition results',
      icon: 'tips',
      steps: [
        'Position the camera straight on so both hands are fully in frame.',
        'Use even, adequate lighting — avoid backlighting.',
        'Keep the background simple with minimal clutter.',
        'Perform gestures clearly and not too quickly.',
        'A quiet environment improves speech recognition accuracy.',
      ]
    },
    {
      id: 'personalize',
      color: '#F97316',
      title: 'Personalize your experience',
      icon: 'personalize',
      steps: [
        'Go to Settings → Personalization to switch Light / Dark mode.',
        'Change display language: Vietnamese or English.',
        'Go to Settings → Subtitle Display to adjust font size and family.',
        'Go to Settings → Devices to change default mic, camera, speaker.',
        'All changes are saved automatically and applied instantly.',
      ]
    },
  ]
};

window.TRANSLATIONS = {
  vi: {
    appName: 'Syltalky',
    tagline: 'Phiên dịch cử chỉ thông minh',
    login: 'Đăng nhập', register: 'Đăng ký',
    emailLabel: 'EMAIL (NHẬP ĐÚNG ĐỊNH DẠNG)',
    passwordLabel: 'MẬT KHẨU',
    confirmLabel: 'XÁC NHẬN MẬT KHẨU',
    rememberMe: 'Ghi nhớ mật khẩu',
    noAccount: 'Chưa có tài khoản?', hasAccount: 'Đã có tài khoản?',
    createAccount: 'Tạo tài khoản mới',
    emailPh: 'email@example.com', passPh: '••••••••',
    errEmailReq: 'Vui lòng nhập địa chỉ email',
    errEmailInvalid: 'Địa chỉ email không hợp lệ',
    errPassReq: 'Vui lòng nhập mật khẩu',
    errPassWrong: 'Sai tên đăng nhập hoặc mật khẩu',
    errPassMismatch: 'Mật khẩu xác nhận không khớp',
    errConfirmReq: 'Vui lòng xác nhận mật khẩu',
    search: 'Tìm kiếm', home: 'Trang chủ', meeting: 'Cuộc họp',
    library: 'Thư viện', guide: 'Hướng dẫn',
    settings: 'Cài đặt', trash: 'Thùng rác', recent: 'Gần đây',
    welcomeBack: 'Chào mừng quay trở lại với Syltalky',
    recentFiles: 'Gần đây', favorites: 'Yêu thích',
    libraryTitle: 'Thư viện',
    folders: 'Thư mục', name: 'Tên', lastMod: 'Ngày chỉnh sửa cuối',
    creatorCol: 'Tên người tạo', addressCol: 'Địa chỉ',
    settingsTitle: 'Cài đặt', overview: 'Tổng quan',
    personalization: 'Cá nhân hóa', devices: 'Thiết bị đầu vào/ra',
    subtitlesDisp: 'Phụ đề hiển thị',
    changeAvatar: 'Thay đổi ảnh đại diện', removeAvatar: 'Xóa ảnh đại diện',
    displayName: 'Tên hiển thị', theme: 'Giao diện', light: 'Sáng', dark: 'Tối',
    language: 'Ngôn ngữ', microphone: 'Microphone', camera: 'Camera', speaker: 'Speaker',
    inputVol: 'Âm lượng đầu vào', outputVol: 'Âm lượng đầu ra',
    cameraPreview: 'Xem trước Camera', fontSize: 'Kích cỡ chữ', fontFamily: 'Font chữ',
    subtitlePreview: 'Xem trước phụ đề',
    previewText: 'Xin chào, tôi đang nói chuyện với bạn.',
    checkDevice: 'Kiểm tra thiết bị', readyToMeet: 'Sẵn sàng họp',
    startMeeting: 'Bắt đầu họp', endMeeting: 'Kết thúc',
    cameraOk: 'Camera hoạt động tốt', micOk: 'Microphone hoạt động tốt',
    meetingTips: 'Lưu ý trước khi vào họp',
    tip1: 'Đảm bảo cả hai tay luôn trong khung hình camera',
    tip2: 'Ánh sáng đầy đủ, tránh ngược sáng',
    tip3: 'Nền sau lưng đơn giản, ít gây nhiễu',
    tip4: 'Thực hiện cử chỉ rõ ràng, tốc độ vừa phải',
    summaryReady: 'Ghi chú và tóm tắt cuộc họp đã sẵn sàng!',
    viewSummary: 'Xem tóm tắt', later: 'Để sau',
    guideTitle: 'Hướng dẫn',
    searchPh: 'Tìm kiếm...', recentSearches: 'Gần đây nhất',
    filterDate: 'Ngày', filterAuthor: 'Tác giả', filterTag: 'Nhãn',
    trashTitle: 'Thùng rác',
    trashPh: 'Tìm trong thùng rác...', restore: 'Hoàn tác', deletePerm: 'Xóa vĩnh viễn',
    trashInfo: 'Các trang trong Thùng rác sẽ bị xóa tự động sau 30 ngày',
    empty: 'Không có mục nào',
    file: 'Tệp', folder: 'Thư mục',
    subtitleLive: 'Xin chào, hệ thống đang hoạt động và nhận diện cử chỉ của bạn...',
    micLevel: 'Mức micro', camStatus: 'Camera', micStatus: 'Micro',
  },
  en: {
    appName: 'Syltalky', tagline: 'Smart gesture translation',
    login: 'Log In', register: 'Sign Up',
    emailLabel: 'EMAIL (VALID FORMAT)', passwordLabel: 'PASSWORD', confirmLabel: 'CONFIRM PASSWORD',
    rememberMe: 'Remember me', noAccount: "Don't have an account?", hasAccount: 'Already have an account?',
    createAccount: 'Create New Account', emailPh: 'email@example.com', passPh: '••••••••',
    errEmailReq: 'Please enter your email', errEmailInvalid: 'Invalid email address',
    errPassReq: 'Please enter your password', errPassWrong: 'Incorrect email or password',
    errPassMismatch: 'Passwords do not match', errConfirmReq: 'Please confirm your password',
    search: 'Search', home: 'Home', meeting: 'Meeting', library: 'Library',
    guide: 'Guide', settings: 'Settings', trash: 'Trash', recent: 'Recent',
    welcomeBack: 'Welcome back to Syltalky', recentFiles: 'Recent', favorites: 'Favorites',
    libraryTitle: 'Library', folders: 'Folders', name: 'Name',
    lastMod: 'Last Modified', creatorCol: 'Creator', addressCol: 'Location',
    settingsTitle: 'Settings', overview: 'Overview', personalization: 'Personalization',
    devices: 'Input/Output Devices', subtitlesDisp: 'Subtitle Display',
    changeAvatar: 'Change Avatar', removeAvatar: 'Remove Avatar',
    displayName: 'Display Name', theme: 'Theme', light: 'Light', dark: 'Dark',
    language: 'Language', microphone: 'Microphone', camera: 'Camera', speaker: 'Speaker',
    inputVol: 'Input Volume', outputVol: 'Output Volume',
    cameraPreview: 'Camera Preview', fontSize: 'Font Size', fontFamily: 'Font Family',
    subtitlePreview: 'Subtitle Preview', previewText: 'Hello, I am speaking to you right now.',
    checkDevice: 'Device Check', readyToMeet: 'Ready to Meet',
    startMeeting: 'Start Meeting', endMeeting: 'End',
    cameraOk: 'Camera working', micOk: 'Microphone working',
    meetingTips: 'Before You Start',
    tip1: 'Keep both hands fully visible in the camera frame',
    tip2: 'Ensure adequate lighting, avoid backlighting',
    tip3: 'Keep the background simple and uncluttered',
    tip4: 'Make gestures clearly at a moderate pace',
    summaryReady: 'Meeting notes and summary are ready!',
    viewSummary: 'View Summary', later: 'Later',
    guideTitle: 'Guide', searchPh: 'Search...', recentSearches: 'Recent',
    filterDate: 'Date', filterAuthor: 'Author', filterTag: 'Tag',
    trashTitle: 'Trash', trashPh: 'Search in Trash...', restore: 'Restore', deletePerm: 'Delete Permanently',
    trashInfo: 'Pages in Trash are automatically deleted after 30 days',
    empty: 'Nothing here', file: 'File', folder: 'Folder',
    subtitleLive: 'Hello, the system is running and recognizing your gestures...',
    micLevel: 'Mic Level', camStatus: 'Camera', micStatus: 'Mic',
  }
};

window.tx = (key, lang) => (window.TRANSLATIONS[lang || 'vi'] || {})[key] || key;
